model:
    backbone: "resnet18"
    embeddings: 256
    
dataset:
    train:
        path: '/home/codahead/Fishial/FishialReaserch/datasets/fishial_75_V1.0'
        json_path: 'data_train.json'
    test:
        path: '/home/codahead/Fishial/FishialReaserch/datasets/fishial_75_V1.0'
        json_path: 'data_test.json'
  
    batchsampler:
        classes_per_batch: 12
        samples_per_class: 10
train:
    loss:
        name: 'qudruplet'
        adaptive_margin: False
    learning_rate: 0.012
    momentum: 0.9
    epoch: 4000
    warmup_steps: 500
    opt_level: 'O2'

output_folder: '/home/fishial/Fishial/output/classification/resnet_18_184_train_06_12'
file_name: 'model_184'
device: 'cuda'
checkpoint: 